// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: proto/scraper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ETCScraper_Scrape_FullMethodName             = "/scraper.ETCScraper/Scrape"
	ETCScraper_ScrapeMultiple_FullMethodName     = "/scraper.ETCScraper/ScrapeMultiple"
	ETCScraper_Health_FullMethodName             = "/scraper.ETCScraper/Health"
	ETCScraper_GetDownloadedFiles_FullMethodName = "/scraper.ETCScraper/GetDownloadedFiles"
)

// ETCScraperClient is the client API for ETCScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ETCScraperClient interface {
	// 単一アカウントのスクレイピング
	Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error)
	// 複数アカウントのスクレイピング
	ScrapeMultiple(ctx context.Context, in *ScrapeMultipleRequest, opts ...grpc.CallOption) (*ScrapeMultipleResponse, error)
	// ヘルスチェック
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ダウンロード済みファイルの取得
	GetDownloadedFiles(ctx context.Context, in *GetDownloadedFilesRequest, opts ...grpc.CallOption) (*GetDownloadedFilesResponse, error)
}

type eTCScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewETCScraperClient(cc grpc.ClientConnInterface) ETCScraperClient {
	return &eTCScraperClient{cc}
}

func (c *eTCScraperClient) Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeResponse)
	err := c.cc.Invoke(ctx, ETCScraper_Scrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTCScraperClient) ScrapeMultiple(ctx context.Context, in *ScrapeMultipleRequest, opts ...grpc.CallOption) (*ScrapeMultipleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeMultipleResponse)
	err := c.cc.Invoke(ctx, ETCScraper_ScrapeMultiple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTCScraperClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ETCScraper_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTCScraperClient) GetDownloadedFiles(ctx context.Context, in *GetDownloadedFilesRequest, opts ...grpc.CallOption) (*GetDownloadedFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadedFilesResponse)
	err := c.cc.Invoke(ctx, ETCScraper_GetDownloadedFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ETCScraperServer is the server API for ETCScraper service.
// All implementations must embed UnimplementedETCScraperServer
// for forward compatibility.
type ETCScraperServer interface {
	// 単一アカウントのスクレイピング
	Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error)
	// 複数アカウントのスクレイピング
	ScrapeMultiple(context.Context, *ScrapeMultipleRequest) (*ScrapeMultipleResponse, error)
	// ヘルスチェック
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ダウンロード済みファイルの取得
	GetDownloadedFiles(context.Context, *GetDownloadedFilesRequest) (*GetDownloadedFilesResponse, error)
	mustEmbedUnimplementedETCScraperServer()
}

// UnimplementedETCScraperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedETCScraperServer struct{}

func (UnimplementedETCScraperServer) Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scrape not implemented")
}
func (UnimplementedETCScraperServer) ScrapeMultiple(context.Context, *ScrapeMultipleRequest) (*ScrapeMultipleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScrapeMultiple not implemented")
}
func (UnimplementedETCScraperServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedETCScraperServer) GetDownloadedFiles(context.Context, *GetDownloadedFilesRequest) (*GetDownloadedFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownloadedFiles not implemented")
}
func (UnimplementedETCScraperServer) mustEmbedUnimplementedETCScraperServer() {}
func (UnimplementedETCScraperServer) testEmbeddedByValue()                    {}

// UnsafeETCScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ETCScraperServer will
// result in compilation errors.
type UnsafeETCScraperServer interface {
	mustEmbedUnimplementedETCScraperServer()
}

func RegisterETCScraperServer(s grpc.ServiceRegistrar, srv ETCScraperServer) {
	// If the following call panics, it indicates UnimplementedETCScraperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ETCScraper_ServiceDesc, srv)
}

func _ETCScraper_Scrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETCScraperServer).Scrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETCScraper_Scrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETCScraperServer).Scrape(ctx, req.(*ScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETCScraper_ScrapeMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeMultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETCScraperServer).ScrapeMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETCScraper_ScrapeMultiple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETCScraperServer).ScrapeMultiple(ctx, req.(*ScrapeMultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETCScraper_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETCScraperServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETCScraper_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETCScraperServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETCScraper_GetDownloadedFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadedFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETCScraperServer).GetDownloadedFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETCScraper_GetDownloadedFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETCScraperServer).GetDownloadedFiles(ctx, req.(*GetDownloadedFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ETCScraper_ServiceDesc is the grpc.ServiceDesc for ETCScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ETCScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.ETCScraper",
	HandlerType: (*ETCScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scrape",
			Handler:    _ETCScraper_Scrape_Handler,
		},
		{
			MethodName: "ScrapeMultiple",
			Handler:    _ETCScraper_ScrapeMultiple_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ETCScraper_Health_Handler,
		},
		{
			MethodName: "GetDownloadedFiles",
			Handler:    _ETCScraper_GetDownloadedFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scraper.proto",
}
