// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_proto_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScrapeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CsvPath       string                 `protobuf:"bytes,3,opt,name=csv_path,json=csvPath,proto3" json:"csv_path,omitempty"`
	CsvContent    string                 `protobuf:"bytes,4,opt,name=csv_content,json=csvContent,proto3" json:"csv_content,omitempty"` // CSVの内容（オプション）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScrapeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScrapeResponse) GetCsvPath() string {
	if x != nil {
		return x.CsvPath
	}
	return ""
}

func (x *ScrapeResponse) GetCsvContent() string {
	if x != nil {
		return x.CsvContent
	}
	return ""
}

type ScrapeMultipleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeMultipleRequest) Reset() {
	*x = ScrapeMultipleRequest{}
	mi := &file_proto_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeMultipleRequest) ProtoMessage() {}

func (x *ScrapeMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeMultipleRequest.ProtoReflect.Descriptor instead.
func (*ScrapeMultipleRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapeMultipleRequest) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ScrapeMultipleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScrapeResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeMultipleResponse) Reset() {
	*x = ScrapeMultipleResponse{}
	mi := &file_proto_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeMultipleResponse) ProtoMessage() {}

func (x *ScrapeMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeMultipleResponse.ProtoReflect.Descriptor instead.
func (*ScrapeMultipleResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *ScrapeMultipleResponse) GetResults() []*ScrapeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScrapeMultipleResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ScrapeMultipleResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ScrapeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CsvPath       string                 `protobuf:"bytes,4,opt,name=csv_path,json=csvPath,proto3" json:"csv_path,omitempty"`
	CsvContent    string                 `protobuf:"bytes,5,opt,name=csv_content,json=csvContent,proto3" json:"csv_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResult) Reset() {
	*x = ScrapeResult{}
	mi := &file_proto_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResult) ProtoMessage() {}

func (x *ScrapeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResult.ProtoReflect.Descriptor instead.
func (*ScrapeResult) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *ScrapeResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScrapeResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScrapeResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScrapeResult) GetCsvPath() string {
	if x != nil {
		return x.CsvPath
	}
	return ""
}

func (x *ScrapeResult) GetCsvContent() string {
	if x != nil {
		return x.CsvContent
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Healthy           bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CurrentJob        *JobStatus             `protobuf:"bytes,3,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	LastSessionFolder string                 `protobuf:"bytes,4,opt,name=last_session_folder,json=lastSessionFolder,proto3" json:"last_session_folder,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetCurrentJob() *JobStatus {
	if x != nil {
		return x.CurrentJob
	}
	return nil
}

func (x *HealthResponse) GetLastSessionFolder() string {
	if x != nil {
		return x.LastSessionFolder
	}
	return ""
}

type JobStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsRunning         bool                   `protobuf:"varint,1,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	StartedAt         string                 `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // ISO8601 format
	TotalAccounts     int32                  `protobuf:"varint,3,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	CompletedAccounts int32                  `protobuf:"varint,4,opt,name=completed_accounts,json=completedAccounts,proto3" json:"completed_accounts,omitempty"`
	SuccessCount      int32                  `protobuf:"varint,5,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount         int32                  `protobuf:"varint,6,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	CurrentAccount    string                 `protobuf:"bytes,7,opt,name=current_account,json=currentAccount,proto3" json:"current_account,omitempty"` // 現在処理中のアカウント（マスク済み）
	LastError         string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`                // 最後のエラーメッセージ
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_proto_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *JobStatus) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *JobStatus) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *JobStatus) GetTotalAccounts() int32 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *JobStatus) GetCompletedAccounts() int32 {
	if x != nil {
		return x.CompletedAccounts
	}
	return 0
}

func (x *JobStatus) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *JobStatus) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *JobStatus) GetCurrentAccount() string {
	if x != nil {
		return x.CurrentAccount
	}
	return ""
}

func (x *JobStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type GetDownloadedFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadedFilesRequest) Reset() {
	*x = GetDownloadedFilesRequest{}
	mi := &file_proto_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadedFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadedFilesRequest) ProtoMessage() {}

func (x *GetDownloadedFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadedFilesRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadedFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{9}
}

type DownloadedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadedFile) Reset() {
	*x = DownloadedFile{}
	mi := &file_proto_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadedFile) ProtoMessage() {}

func (x *DownloadedFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadedFile.ProtoReflect.Descriptor instead.
func (*DownloadedFile) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadedFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadedFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetDownloadedFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*DownloadedFile      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	SessionFolder string                 `protobuf:"bytes,2,opt,name=session_folder,json=sessionFolder,proto3" json:"session_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadedFilesResponse) Reset() {
	*x = GetDownloadedFilesResponse{}
	mi := &file_proto_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadedFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadedFilesResponse) ProtoMessage() {}

func (x *GetDownloadedFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadedFilesResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadedFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *GetDownloadedFilesResponse) GetFiles() []*DownloadedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetDownloadedFilesResponse) GetSessionFolder() string {
	if x != nil {
		return x.SessionFolder
	}
	return ""
}

// ストリーミングダウンロード用メッセージ
type StreamDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionFolder string                 `protobuf:"bytes,1,opt,name=session_folder,json=sessionFolder,proto3" json:"session_folder,omitempty"` // 空の場合は最新セッション
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDownloadRequest) Reset() {
	*x = StreamDownloadRequest{}
	mi := &file_proto_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadRequest) ProtoMessage() {}

func (x *StreamDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadRequest.ProtoReflect.Descriptor instead.
func (*StreamDownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *StreamDownloadRequest) GetSessionFolder() string {
	if x != nil {
		return x.SessionFolder
	}
	return ""
}

type StreamDownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                             // ファイル名（最初のチャンクで設定）
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                     // ファイルデータのチャンク
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                // ファイル内のオフセット
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`         // ファイルの総サイズ
	IsLastChunk   bool                   `protobuf:"varint,5,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"` // このファイルの最後のチャンクかどうか
	FileIndex     int32                  `protobuf:"varint,6,opt,name=file_index,json=fileIndex,proto3" json:"file_index,omitempty"`         // 現在のファイルインデックス（0始まり）
	TotalFiles    int32                  `protobuf:"varint,7,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`      // 総ファイル数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDownloadChunk) Reset() {
	*x = StreamDownloadChunk{}
	mi := &file_proto_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadChunk) ProtoMessage() {}

func (x *StreamDownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadChunk.ProtoReflect.Descriptor instead.
func (*StreamDownloadChunk) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *StreamDownloadChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StreamDownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamDownloadChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamDownloadChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *StreamDownloadChunk) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *StreamDownloadChunk) GetFileIndex() int32 {
	if x != nil {
		return x.FileIndex
	}
	return 0
}

func (x *StreamDownloadChunk) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

var File_proto_scraper_proto protoreflect.FileDescriptor

const file_proto_scraper_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scraper.proto\x12\ascraper\"D\n" +
	"\rScrapeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x80\x01\n" +
	"\x0eScrapeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bcsv_path\x18\x03 \x01(\tR\acsvPath\x12\x1f\n" +
	"\vcsv_content\x18\x04 \x01(\tR\n" +
	"csvContent\"E\n" +
	"\x15ScrapeMultipleRequest\x12,\n" +
	"\baccounts\x18\x01 \x03(\v2\x10.scraper.AccountR\baccounts\">\n" +
	"\aAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x8f\x01\n" +
	"\x16ScrapeMultipleResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.scraper.ScrapeResultR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x97\x01\n" +
	"\fScrapeResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\bcsv_path\x18\x04 \x01(\tR\acsvPath\x12\x1f\n" +
	"\vcsv_content\x18\x05 \x01(\tR\n" +
	"csvContent\"\x0f\n" +
	"\rHealthRequest\"\xa9\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x123\n" +
	"\vcurrent_job\x18\x03 \x01(\v2\x12.scraper.JobStatusR\n" +
	"currentJob\x12.\n" +
	"\x13last_session_folder\x18\x04 \x01(\tR\x11lastSessionFolder\"\xab\x02\n" +
	"\tJobStatus\x12\x1d\n" +
	"\n" +
	"is_running\x18\x01 \x01(\bR\tisRunning\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\tR\tstartedAt\x12%\n" +
	"\x0etotal_accounts\x18\x03 \x01(\x05R\rtotalAccounts\x12-\n" +
	"\x12completed_accounts\x18\x04 \x01(\x05R\x11completedAccounts\x12#\n" +
	"\rsuccess_count\x18\x05 \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x06 \x01(\x05R\tfailCount\x12'\n" +
	"\x0fcurrent_account\x18\a \x01(\tR\x0ecurrentAccount\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\"\x1b\n" +
	"\x19GetDownloadedFilesRequest\"F\n" +
	"\x0eDownloadedFile\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"r\n" +
	"\x1aGetDownloadedFilesResponse\x12-\n" +
	"\x05files\x18\x01 \x03(\v2\x17.scraper.DownloadedFileR\x05files\x12%\n" +
	"\x0esession_folder\x18\x02 \x01(\tR\rsessionFolder\">\n" +
	"\x15StreamDownloadRequest\x12%\n" +
	"\x0esession_folder\x18\x01 \x01(\tR\rsessionFolder\"\xe0\x01\n" +
	"\x13StreamDownloadChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\"\n" +
	"\ris_last_chunk\x18\x05 \x01(\bR\visLastChunk\x12\x1d\n" +
	"\n" +
	"file_index\x18\x06 \x01(\x05R\tfileIndex\x12\x1f\n" +
	"\vtotal_files\x18\a \x01(\x05R\n" +
	"totalFiles2\x86\x03\n" +
	"\n" +
	"ETCScraper\x129\n" +
	"\x06Scrape\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponse\x12Q\n" +
	"\x0eScrapeMultiple\x12\x1e.scraper.ScrapeMultipleRequest\x1a\x1f.scraper.ScrapeMultipleResponse\x129\n" +
	"\x06Health\x12\x16.scraper.HealthRequest\x1a\x17.scraper.HealthResponse\x12]\n" +
	"\x12GetDownloadedFiles\x12\".scraper.GetDownloadedFilesRequest\x1a#.scraper.GetDownloadedFilesResponse\x12P\n" +
	"\x0eStreamDownload\x12\x1e.scraper.StreamDownloadRequest\x1a\x1c.scraper.StreamDownloadChunk0\x01B\x1cZ\x1agithub.com/scrape-vm/protob\x06proto3"

var (
	file_proto_scraper_proto_rawDescOnce sync.Once
	file_proto_scraper_proto_rawDescData []byte
)

func file_proto_scraper_proto_rawDescGZIP() []byte {
	file_proto_scraper_proto_rawDescOnce.Do(func() {
		file_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)))
	})
	return file_proto_scraper_proto_rawDescData
}

var file_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_scraper_proto_goTypes = []any{
	(*ScrapeRequest)(nil),              // 0: scraper.ScrapeRequest
	(*ScrapeResponse)(nil),             // 1: scraper.ScrapeResponse
	(*ScrapeMultipleRequest)(nil),      // 2: scraper.ScrapeMultipleRequest
	(*Account)(nil),                    // 3: scraper.Account
	(*ScrapeMultipleResponse)(nil),     // 4: scraper.ScrapeMultipleResponse
	(*ScrapeResult)(nil),               // 5: scraper.ScrapeResult
	(*HealthRequest)(nil),              // 6: scraper.HealthRequest
	(*HealthResponse)(nil),             // 7: scraper.HealthResponse
	(*JobStatus)(nil),                  // 8: scraper.JobStatus
	(*GetDownloadedFilesRequest)(nil),  // 9: scraper.GetDownloadedFilesRequest
	(*DownloadedFile)(nil),             // 10: scraper.DownloadedFile
	(*GetDownloadedFilesResponse)(nil), // 11: scraper.GetDownloadedFilesResponse
	(*StreamDownloadRequest)(nil),      // 12: scraper.StreamDownloadRequest
	(*StreamDownloadChunk)(nil),        // 13: scraper.StreamDownloadChunk
}
var file_proto_scraper_proto_depIdxs = []int32{
	3,  // 0: scraper.ScrapeMultipleRequest.accounts:type_name -> scraper.Account
	5,  // 1: scraper.ScrapeMultipleResponse.results:type_name -> scraper.ScrapeResult
	8,  // 2: scraper.HealthResponse.current_job:type_name -> scraper.JobStatus
	10, // 3: scraper.GetDownloadedFilesResponse.files:type_name -> scraper.DownloadedFile
	0,  // 4: scraper.ETCScraper.Scrape:input_type -> scraper.ScrapeRequest
	2,  // 5: scraper.ETCScraper.ScrapeMultiple:input_type -> scraper.ScrapeMultipleRequest
	6,  // 6: scraper.ETCScraper.Health:input_type -> scraper.HealthRequest
	9,  // 7: scraper.ETCScraper.GetDownloadedFiles:input_type -> scraper.GetDownloadedFilesRequest
	12, // 8: scraper.ETCScraper.StreamDownload:input_type -> scraper.StreamDownloadRequest
	1,  // 9: scraper.ETCScraper.Scrape:output_type -> scraper.ScrapeResponse
	4,  // 10: scraper.ETCScraper.ScrapeMultiple:output_type -> scraper.ScrapeMultipleResponse
	7,  // 11: scraper.ETCScraper.Health:output_type -> scraper.HealthResponse
	11, // 12: scraper.ETCScraper.GetDownloadedFiles:output_type -> scraper.GetDownloadedFilesResponse
	13, // 13: scraper.ETCScraper.StreamDownload:output_type -> scraper.StreamDownloadChunk
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_scraper_proto_init() }
func file_proto_scraper_proto_init() {
	if File_proto_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scraper_proto_goTypes,
		DependencyIndexes: file_proto_scraper_proto_depIdxs,
		MessageInfos:      file_proto_scraper_proto_msgTypes,
	}.Build()
	File_proto_scraper_proto = out.File
	file_proto_scraper_proto_goTypes = nil
	file_proto_scraper_proto_depIdxs = nil
}
